# -*- coding: utf-8 -*-
"""escala_grises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icwURd7p2TSal3ZRprdfVggvk9TUbhhw
"""

import numpy as np
import time
import sys
from mpi4py import MPI

def transformar_escala_grises_secuencial(imagen_rgb):
    """Ejecución secuencial pura. Extrae las dimensiones dinámicamente."""
    start_time = time.perf_counter()

    # Separación de canales basada en la forma real de la imagen
    R = imagen_rgb[:, :, 0]
    G = imagen_rgb[:, :, 1]
    B = imagen_rgb[:, :, 2]
    imagen_gris = (0.299 * R + 0.587 * G + 0.114 * B).astype(np.uint8)

    end_time = time.perf_counter()
    return imagen_gris, end_time - start_time

def transformar_escala_grises_mpi(imagen_rgb):
    """Ejecución paralela distribuida. El tamaño se adapta a la imagen provista."""
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()

    if rank == 0:
        # Se segmenta dinámicamente sin importar el tamaño
        bloques_filas = np.array_split(imagen_rgb, size, axis=0)
    else:
        bloques_filas = None

    start_time = time.perf_counter()

    mi_bloque_rgb = comm.scatter(bloques_filas, root=0)

    R = mi_bloque_rgb[:, :, 0]
    G = mi_bloque_rgb[:, :, 1]
    B = mi_bloque_rgb[:, :, 2]
    mi_bloque_gris = (0.299 * R + 0.587 * G + 0.114 * B).astype(np.uint8)

    bloques_grises_procesados = comm.gather(mi_bloque_gris, root=0)

    end_time = time.perf_counter()
    duracion = end_time - start_time

    if rank == 0:
        imagen_gris_final = np.vstack(bloques_grises_procesados)
        return imagen_gris_final, duracion
    return None, duracion

if __name__ == "__main__":
    modo = sys.argv[1] if len(sys.argv) > 1 else "--seq"

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()

    imagen_prueba = None
    if rank == 0:
        if len(sys.argv) > 2:
            from PIL import Image
            ruta_img = sys.argv[2]
            print(f"[Raíz] Cargando imagen real desde: {ruta_img}")
            imagen_prueba = np.array(Image.open(ruta_img).convert("RGB"))
        else:
            print("[Raíz] Sin imagen externa. Generando matriz sintética predeterminada de 400x600...")
            imagen_prueba = np.random.randint(0, 256, (400, 600, 3), dtype=np.uint8)

    if modo == "--seq" and rank == 0:
        print("=== INICIANDO PROCESAMIENTO SECUENCIAL (ESCALA DE GRISES) ===")
        print(f"[Raíz] Dimensiones dinámicas detectadas: {imagen_prueba.shape}")
        resultado, t_seq = transformar_escala_grises_secuencial(imagen_prueba)
        print("¡Filtro Secuencial completado con éxito!")
        print(f"Tiempo total de ejecución Secuencial: {t_seq:.6f} segundos.")

        if len(sys.argv) > 2:
          from PIL import Image
          # Cambiamos el destino a la carpeta de resultados
          Image.fromarray(resultado).save("resultados/resultado_gris.jpg")
          print("[Raíz] Copia guardada con éxito en 'resultados/resultado_gris.jpg'")

    elif modo == "--mpi":
        if rank == 0:
            print(f"=== INICIANDO PROCESAMIENTO DISTRIBUIDO CON {comm.Get_size()} PROCESOS ===")
            print(f"[Raíz] Dimensiones dinámicas detectadas: {imagen_prueba.shape}")

        resultado, t_mpi = transformar_escala_grises_mpi(imagen_prueba)

        if rank == 0:
            print("[Raíz] ¡Procesamiento completado con éxito!")
            print(f"Tiempo total de ejecución MPI: {t_mpi:.6f} segundos.")

            if len(sys.argv) > 2 and resultado is not None:
              from PIL import Image
              # Cambiamos el destino a la carpeta de resultados
              Image.fromarray(resultado).save("resultados/resultado_gris.jpg")
              print("[Raíz] Copia distribuida guardada con éxito en 'resultados/resultado_gris.jpg'")